name: deploy to remote

on:
  push:
    branches:
      - lightsail

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: snyk/actions/setup@master
      - name: gulp build
        uses: actions/setup-node@v2
      - run: yarn install && yarn build
      - name: Run lint and prettier
        run: yarn lint
      - name: yarn test
        run: yarn test
      - name: Snyk monitor
        run: snyk test
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" --delete ./dist/* bitnami@3.114.21.151:/opt/bitnami/nginx/html/15puzzle/
